name: Checkov Security Scan

on:
  push:
    branches:
      - main
    tags:
      - 'v*'    
  pull_request:
    types:
      - opened
      - synchronize
      - reopened  
  workflow_dispatch: 

permissions:
  contents: read
  security-events: write

jobs:
  checkov-scan:
    name: Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Install Checkov
        run: pip install checkov==3.2.432

      # Run Checkov with SARIF output
      - name: Run Checkov and generate SARIF report
        run: |
          checkov -d ./ \
            -o sarif \
            --output-file checkov-results.sarif \
            --quiet

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@b0565cb28b456da32509aef995361ffcc63f40b0 # v3.28.15
        with:
          sarif_file: checkov-results.sarif

      - name: Show Checkov results (verbose)
        run: checkov -d ./
