name: Resposta Automática a Issues

on:
  issues:
    types: [opened]
permissions:
  contents: read
  issues: write  
  
jobs:
  resposta-automatica:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: derekprior/add-autoresponse@500f8788d667c31d43a4469f8a3ec3b491470fd1 # master
      env:
        GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "Obrigado @${{ github.event.issue.user.login }} por criar esta issue. Se esta issue é sobre um bug, pergunta sobre o produto ou solicitação de funcionalidade: você pode me enviar um e-mail para contato@nataliagranato.xyz"
        author: ${{ github.event.issue.user.login }}
